version: '3.9'
services:
  backend:
    container_name: app_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    working_dir: /app-backend
    volumes: 
      - ./:/app-backend/
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0.37
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=be_mobile_api
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
volumes:
  db_data:
